### ISSUE TITLE
No meta generated by accessor's methods

### ISSUE THREAD

**Issue by hombit** [lincc-frameworks/nested-dask#74]
**Bug report**

I tried to call `.nest.to_flat()` on a nested series, but it failed because no meta is provided.

**Before submitting**
Please check the following:

- [ ] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [ ] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a description of what I expected instead.
- [ ] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.
